// app/src/components/layouts/Footer.vue
<template>
  <div class="global-footer-component">
    <b-container fluid>
      <b-col cols="12">
        <hr/>
      </b-col>
    </b-container>
    <b-container fluid>
      <b-row>
        <b-col cols="12" lg="2">
          <div class="d-flex align-items-center justify-content-center">
            <img alt="Vue logo" src="../../assets/logo.png" class="w-25">
          </div>
        </b-col>
        <b-col cols="12" lg="10">
          <b-row>
            <b-col cols="12" lg="3" class="d-flex align-items-center justify-content-center">
              <a href="#">
                <span>Politique de confidentialité</span>
              </a>
            </b-col>
            <b-col cols="12" lg="3" class="d-flex align-items-center justify-content-center">
              <a href="#">
                <span>Qui-sommes nous ?</span>
              </a>
            </b-col>
            <b-col cols="12" lg="3" class="d-flex align-items-center justify-content-center">
              <a href="#">
                <span>Mentions légales</span>
              </a>
            </b-col>
            <b-col cols="12" lg="3" class="d-flex align-items-center justify-content-center">
              <a href="#">
                <span>Mentions illégales</span>
              </a>
            </b-col>
          </b-row>
          <b-row class="mt-lg-4">
            <b-col cols="12" lg="3" class="d-flex align-items-center justify-content-center">
              <a href="#">
                <span>Répertoire Github</span>
              </a>
            </b-col>
            <b-col cols="12" lg="3" class="d-flex align-items-center justify-content-center">
              <a href="#">
                <span>Règles d'utilisations</span>
              </a>
            </b-col>
            <b-col cols="12" lg="3" class="d-flex align-items-center justify-content-center">
              <a href="#">
                <span>Utilisation des cookies</span>
              </a>
            </b-col>
            <b-col cols="12" lg="3" class="d-flex align-items-center justify-content-center">
              <a href="#">
                <span>Règles de gestion</span>
              </a>
            </b-col>
          </b-row>
        </b-col>
      </b-row>
      <b-col cols="12" class="d-flex justify-content-center mt-5">
        <h6>Proceos - Open-Source. 2021-2022.</h6>
      </b-col>
    </b-container>
  </div>
</template>

<script>
export default {
  name: "Footer"
}
</script>

<style scoped>

.global-footer-component{}

</style>

// react-app/src/components/layouts/Footer.js
import React from "react"

// Assets
import Logo from "../../assets/proceos.png"

export default function Footer() {

    return(
        <>
            <footer>
                <div className="mt-5 pb-3">
                    <div className="container-fluid">
                        <hr/>
                        <div className="row">
                            <div className="col-12 col-md-3">
                                <img src={Logo} width="128" height="128" className="App-logo" alt="Logo de l'application"/>
                            </div>
                            <div className="col-12 col-md-6 h-100">
                                <div className="d-flex flex-column align-items-center justify-content-center pt-4">
                                    <div>
                                        <h6>Proceos</h6>
                                    </div>
                                    <div>
                                        <span>Open-Source Project 2021-2022</span>
                                    </div>
                                </div>

                            </div>
                            <div className="col-12 col-md-3 h-100 pt-3">
                                <div>
                                    <a href="/">Politique de confidentialité</a>
                                </div>
                                <div>
                                    <a href="/">Mentions légales</a>
                                </div>
                                <div>
                                    <a href="/">Conditions d'utilisation</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </footer>
        </>
    )
}
